import { makeDefaultVfo, BOOKMARK_CATEGORIES } from './constants';
import type { ReceiverAudioSessionRecord, ReceiverMarker, ReceiverMarkerSet, ReceiverScanRecord } from './receiver-records-api';
import type { SweepCandidate, SweepProgress, SweepSource, SweepSpectrumView } from '../worker/sweep-types';

export function createAppData() {
	return {
		backend: null as any,
		connected: false,
		running: false,
		isOnline: navigator.onLine,
		remoteMode: 'none' as 'none' | 'host' | 'client',
		activeWorkspace: 'spectrum' as 'spectrum' | 'listener' | 'records',
		remoteStatus: '',
		remoteLink: '',
		copyLinkSuccess: false,
		copyLinkTooltip: 'Copy link',
		remoteClients: [] as Array<{ id: string; connectedAt: number; country: string; vfoCount: number; firstFreq: number | null; isRelay: boolean }>,
		showRemoteClientsDialog: false,
		showRemoteConnectDialog: false,
		remoteConnectId: '',
		recentRemoteIds: [] as string[],
		remotePeerId: '',
		snackbar: { show: false, message: "" },
		audioUnlockPendingId: null as string | null,
		radio: {
			centerFreq: 100.0,
			frequencyShift: 0.0,
			sampleRate: 20000000,
			fftSize: 65536,
			iqCorrection: true,
		},
		display: {
			minDB: -70.0,
			maxDB: 0.0,
		},
		gains: {} as Record<string, number>,
		deviceCapabilities: null as any,
		records: {
			settingsLoaded: false,
			autoSpectrumRecording: false,
			savedAutoSpectrumRecording: false,
			loading: false,
			error: '',
			scanItems: [] as ReceiverScanRecord[],
			scanTotal: 0,
			scanPage: 0,
			audioItems: [] as ReceiverAudioSessionRecord[],
			audioTotal: 0,
			audioPage: 0,
			pageSize: 20,
			markerSets: [] as ReceiverMarkerSet[],
			selectedMarkerSetId: '',
			markerSetName: '',
			markers: [] as ReceiverMarker[],
			selectedMarkerId: null as string | null,
			referenceMarkerId: null as string | null,
			markerFrequencyDrafts: {} as Record<string, string>,
			manualMarkerFrequencyMHz: '',
			manualMarkerLabel: '',
			markedOnly: false,
		},
		audioRecording: {
			armed: false,
			starting: false,
			stopping: false,
			sessionId: null as string | null,
			error: '',
		},

		sweep: {
			active: false,
			starting: false,
			stopping: false,
			stopPhase: '' as 'rf' | 'archive' | 'finalize' | '',
			returnToRx: false,
			hasResults: false,
			offlineSessionName: '',
			visualization: 'spectrum' as 'spectrum' | 'waterfall',
			waterfallRows: 0,
			listening: false,
			listenStarting: false,
			listenFrequencyHz: 0,
			listenMode: '',
			source: 'simulated' as SweepSource,
			startMHz: 100,
			endMHz: 1000,
			fftSize: 8192 as 4096 | 8192,
			lnaGain: 40,
			vgaGain: 20,
			ampEnabled: false,
			minSnrDb: 8,
			minimumPeakDb: -80,
			displayMinDb: -120,
			displayMaxDb: 0,
			averageAlpha: 0.35,
			view: 'average' as SweepSpectrumView,
			sortBy: 'snr' as 'frequency' | 'peak' | 'snr' | 'hits' | 'lastSeen',
			scanId: null as string | null,
			archive: false,
			candidateTotal: 0,
			candidateHistoryTotal: 0,
			candidatePage: 0,
			candidatePageSize: 100,
			candidatePageFromStore: false,
			candidatesLoading: false,
			candidates: [] as SweepCandidate[],
			selectedCandidate: null as SweepCandidate | null,
			error: '',
			viewportStartHz: 100_000_000,
			viewportEndHz: 1_000_000_000,
			hoverFrequencyHz: null as number | null,
			hoverPowerDb: null as number | null,
			progress: {
				sweepCount: 0,
				sweepsPerSecond: 0,
				currentFrequencyHz: 0,
				bytesPerSecond: 0,
				detectedCount: 0,
				discardedBytes: 0,
			} as SweepProgress,
		},
		locks: {
			centerFreq: false,
			sampleRate: false,
		} as Record<string, boolean>,
		vfos: [makeDefaultVfo(100.0)],
		activeVfoIndex: 0,
		info: { boardName: "" },
		hoverFreqText: "",
		dspStats: null as any,
		showStats: false,
		fps: 0,
		vfoSquelchOpen: [] as boolean[],
		vfoSquelchHangUntil: [] as number[],
		vfoActivityStats: [] as Array<{ count: number; totalMs: number; squelchOpenSince: number | null }>,
		autoSquelchSamples: [] as Array<number[]>,
		autoSquelchActive: [] as boolean[],
		activityNow: 0,
		showActivity: false,
		view: {
			zoomScale: 1.0,
			zoomOffset: 0.0,
			locked: false
		},
		whisper: {
			panelOpen: false,
			active: false,
			status: 'idle' as string,
			loadProgress: 0,
			loadPhase: 'downloading' as string,
			loadFile: '',
			loadFilesDone: 0,
			loadFilesTotal: 0,
			model: 'onnx-community/whisper-small',
			chunkSeconds: 10,
			log: [] as Array<{ time: string; freq: string; text: string; duration: string; transcribeTime?: string; vfoIndex?: number | null }>,
			statusMsg: '',
			recording: false,
			transcribing: false,
			recordStart: null as Date | null,
			recordDuration: 0,
			pendingChunks: 0,
		},
		pocsag: {
			panelOpen: false,
			log: [] as Array<{ time: string; freq: string; vfoIndex: number; capcode: string; type: string; text: string; baud: number }>,
		},
		bookmarkCategories: BOOKMARK_CATEGORIES,
		bookmarkCategoryFilter: '',
		bookmarkSearch: '',
		bookmarks: [] as any[],
		bookmarkModal: { show: false, type: 'individual', name: '', category: '' },
		bookmarkImportModal: { show: false },
		bookmarkEdit: {
			show: false,
			index: -1,
			type: 'individual',
			name: '',
			category: '',
			// individual fields
			freq: 100.0,
			mode: 'nfm',
			bandwidth: 12500,
			snapInterval: 2500,
			deEmphasis: 'none',
			squelchEnabled: false,
			squelchLevel: -100,
			noiseReduction: false,
			stereo: false,
			lowPass: true,
			highPass: false,
			rds: false,
			rdsRegion: 'eu',
			volume: 50,
			// group fields
			centerFreq: 100.0,
			sampleRate: 8000000,
			vfos: [] as any[],
			activeVfoIndex: 0,
		},
		devicePicker: {
			show: false,
			devices: [] as Array<{ device: USBDevice; driverName: string; productName: string }>,
		},
		sidebarOpen: false,

		collapsedPanels: {} as Record<string, boolean>,
		vfoConflictDialog: {
			show: false,
			vfoIndex: -1,
			requestedFreq: 0,
			previousFreq: 0,
			optionA: null as { centerFreq: number; description: string } | null,
			optionB: null as { centerFreq: number; description: string; excludedVfos: number[] } | null,
		},
	};
}
